version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: apex-db
    restart: always
    environment:
      POSTGRES_USER: apex_user
      POSTGRES_PASSWORD: apex_password
      POSTGRES_DB: apex_platform
    ports:
      - "7000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: apex-redis
    ports:
      - "7001:6379"

  minio:
    image: minio/minio
    container_name: apex-minio
    ports:
      - "7002:9000"
      - "7003:9001"
    environment:
      MINIO_ROOT_USER: apex_minio_user
      MINIO_ROOT_PASSWORD: apex_minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  adminer:
    image: adminer
    container_name: apex-adminer
    restart: always
    ports:
      - "7004:8080"

volumes:
  postgres_data:
  minio_data:
